(function(global){
'use strict';
const FORMAT_ID='ARCHITECT_ENCRYPTED_PORTABLE_BACKUP';
const ENVELOPE_VERSION=1;
const APP_SCHEMA_VERSION=2;
const MAX_BACKUP_BYTES=25*1024*1024;
const MAX_OBJECTS=50000;
const te=new TextEncoder(); const td=new TextDecoder();
const DEFAULT_KDF={id:'PBKDF2-SHA-256',iterations:210000,hash:'SHA-256',saltBytes:16};
const ALG={id:'AES-256-GCM',name:'AES-GCM',ivBytes:12,tagLength:128};
const STORES=['insights','dreams','patterns','evolution','spiritual','checkins','spheres','sphereLogs','bots','chapters','digests','chats','cravings','oq','vit','env','_del','__ts'];
const CFG_EXCLUDE=new Set(['spaceKey','apiUrl','lastSync','_ts','passphrase','recoveryKey','backendToken','apiKey','aiKey','providerKey','syncPassphrase']);
const PUBLIC_ERRORS={bad_password:'Не удалось расшифровать: пароль неверен или файл повреждён',unsupported_version:'Версия зашифрованной копии не поддерживается',bad_format:'Это не файл зашифрованной копии Архитектора',too_large:'Файл больше поддерживаемого лимита',manifest_mismatch:'Проверка целостности копии не прошла',quota:'Недостаточно места для восстановления'};
function bytesToB64(bytes){let s=''; for(const b of bytes)s+=String.fromCharCode(b); return btoa(s);}
function b64ToBytes(b64){const s=atob(b64); const a=new Uint8Array(s.length); for(let i=0;i<s.length;i++)a[i]=s.charCodeAt(i); return a;}
function clone(v){return JSON.parse(JSON.stringify(v));}
function safeCfg(cfg={}){const out={}; for(const [k,v] of Object.entries(cfg||{})) if(!CFG_EXCLUDE.has(k)) out[k]=v; return out;}
function selectedDb(db={}){const out={}; for(const k of STORES) out[k]=clone(db[k]); return out;}
function collectMediaRefs(db={}){const refs=new Set(); const walk=v=>{ if(!v)return; if(Array.isArray(v)) return v.forEach(walk); if(typeof v==='object'){ if(Array.isArray(v.media)) v.media.forEach(id=>refs.add(String(id))); Object.values(v).forEach(walk); } }; walk(db); return [...refs].sort();}
async function sha256B64(data){const buf=typeof data==='string'?te.encode(data):data; return bytesToB64(new Uint8Array(await crypto.subtle.digest('SHA-256',buf)));}
async function derive(password,salt,kdf=DEFAULT_KDF){ if(!password||String(password).length<8) throw new Error('password_too_short'); if(kdf.id!==DEFAULT_KDF.id||kdf.hash!=='SHA-256'||kdf.iterations<100000||kdf.iterations>1000000) throw new Error('bad_kdf'); const base=await crypto.subtle.importKey('raw',te.encode(password),'PBKDF2',false,['deriveKey']); return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:kdf.iterations,hash:kdf.hash},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
function countManifest(payload){const db=payload.db||{}; const stores={}; let objects=0; for(const [k,v] of Object.entries(db)){ const count=Array.isArray(v)?v.length:(v&&typeof v==='object'?Object.keys(v).length:(v===undefined?0:1)); stores[k]=count; objects+=count; } if(objects>MAX_OBJECTS) throw new Error('too_many_objects'); return stores;}
async function mediaEntries(mediaRefs,mediaGet){const entries=[]; const missing=[]; for(const id of mediaRefs){ let obj=null; try{obj=mediaGet?await mediaGet(id):null;}catch(e){obj=null;} if(!obj){missing.push({id}); continue;} const json=JSON.stringify(obj); entries.push({id,mime:obj.mime||obj.type||'application/octet-stream',size:te.encode(json).byteLength,sha256:await sha256B64(json),object:obj}); } return {entries,missing};}
async function createBackup({profileId,db,cfg,password,mode='data',mediaGet,now=new Date().toISOString()}={}){ if(!profileId) throw new Error('profile_required'); if(!['data','complete'].includes(mode)) throw new Error('bad_mode'); const mediaRefs=collectMediaRefs(db); const media=mode==='complete'?await mediaEntries(mediaRefs,mediaGet):{entries:[],missing:mediaRefs.map(id=>({id,incomplete:true}))}; const payload={schemaVersion:APP_SCHEMA_VERSION,profile:{id:profileId},db:selectedDb(db),cfg:safeCfg(cfg),media:{mode,entries:media.entries,missing:media.missing}}; const manifest={stores:countManifest(payload),mediaRefs,mediaCount:media.entries.length,missingMedia:media.missing,mode,createdAt:now}; manifest.digest=await sha256B64(JSON.stringify({payload,manifest:{...manifest,digest:undefined}})); const plaintext=JSON.stringify({payload,manifest}); const salt=crypto.getRandomValues(new Uint8Array(DEFAULT_KDF.saltBytes)); const iv=crypto.getRandomValues(new Uint8Array(ALG.ivBytes)); const key=await derive(password,salt); const aad=te.encode(JSON.stringify({format:FORMAT_ID,version:ENVELOPE_VERSION,mode})); const ciphertext=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:aad,tagLength:ALG.tagLength},key,te.encode(plaintext))); return {format:FORMAT_ID,version:ENVELOPE_VERSION,createdAt:now,appSchemaVersion:APP_SCHEMA_VERSION,mode,kdf:DEFAULT_KDF,salt:bytesToB64(salt),algorithm:ALG,iv:bytesToB64(iv),manifestDigest:manifest.digest,metadata:{ciphertextBytes:ciphertext.byteLength,storeCount:Object.keys(manifest.stores).length,mediaCount:media.entries.length,missingMediaCount:media.missing.length,maxSupportedBytes:MAX_BACKUP_BYTES},ciphertext:bytesToB64(ciphertext)};}
function validateEnvelope(env,size=0){ if(!env||env.format!==FORMAT_ID) throw publicError('bad_format'); if(env.version!==ENVELOPE_VERSION) throw publicError('unsupported_version'); if(size>MAX_BACKUP_BYTES) throw publicError('too_large'); if(!env.ciphertext||!env.salt||!env.iv) throw publicError('bad_format'); }
function publicError(code){const e=new Error(PUBLIC_ERRORS[code]||'Ошибка зашифрованной копии'); e.code=code; return e;}
async function decryptBackup(env,password,{size=0}={}){ validateEnvelope(env,size); let text; try{ const key=await derive(password,b64ToBytes(env.salt),env.kdf); const aad=te.encode(JSON.stringify({format:FORMAT_ID,version:env.version,mode:env.mode})); const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64ToBytes(env.iv),additionalData:aad,tagLength:ALG.tagLength},key,b64ToBytes(env.ciphertext)); text=td.decode(plain); }catch(e){throw publicError('bad_password');} const parsed=JSON.parse(text); const expected=await sha256B64(JSON.stringify({payload:parsed.payload,manifest:{...parsed.manifest,digest:undefined}})); if(expected!==parsed.manifest.digest||expected!==env.manifestDigest) throw publicError('manifest_mismatch'); return parsed;}
async function planRestore(env,password,opts){const dec=await decryptBackup(env,password,opts); return {summary:{mode:dec.manifest.mode,stores:dec.manifest.stores,mediaCount:dec.manifest.mediaCount,missingMedia:dec.manifest.missingMedia},decrypted:dec};}
async function restore({decrypted,targetProfileId,replace=false,storage,mediaPut}={}){ if(!decrypted||!storage) throw new Error('restore_required'); const id=targetProfileId||('p-restored-'+Date.now()); const snapKey='arch5_pre_restore_'+id+'_'+Date.now(); const current=storage.getItem('arch5_db_'+id); if(current&&!replace) throw new Error('target_not_empty'); storage.setItem(snapKey, JSON.stringify({db:current,cfg:storage.getItem('arch5_cfg_'+id)})); try{ storage.setItem('arch5_db_'+id,JSON.stringify(decrypted.payload.db)); storage.setItem('arch5_cfg_'+id,JSON.stringify(decrypted.payload.cfg)); for(const m of decrypted.payload.media.entries||[]) if(mediaPut) await mediaPut(m.id,m.object); JSON.parse(storage.getItem('arch5_db_'+id)); return {profileId:id,snapshotKey:snapKey,activated:true}; }catch(e){ if(current==null) storage.removeItem('arch5_db_'+id); else storage.setItem('arch5_db_'+id,current); throw e; }}
global.ARCH_BACKUP={FORMAT_ID,ENVELOPE_VERSION,MAX_BACKUP_BYTES,STORES,DEFAULT_KDF,ALG,safeCfg,selectedDb,collectMediaRefs,createBackup,decryptBackup,planRestore,restore,validateEnvelope,PUBLIC_ERRORS};
})(typeof globalThis!=='undefined'?globalThis:window);
