import { webcrypto as nodeCrypto } from 'node:crypto';
const cryptoImpl = globalThis.crypto || nodeCrypto;
const te = new TextEncoder();
const td = new TextDecoder();
export const BACKUP_SCHEMA_VERSION = 1;
export const BACKUP_KDF_ITERATIONS = 600000;
export const BACKUP_LIMITS = Object.freeze({ maxCiphertextBytes: 50*1024*1024, maxJsonBytes: 25*1024*1024, maxCollections: 64, maxObjects: 20000, maxMediaCount: 2000, maxMediaBytes: 25*1024*1024, maxTotalMediaBytes: 50*1024*1024 });
const b64re=/^[A-Za-z0-9+/]*={0,2}$/;
export function toBase64(bytes){ bytes = asBytes(bytes); let s=''; for(let i=0;i<bytes.length;i+=0x8000) s+=String.fromCharCode(...bytes.slice(i,i+0x8000)); return btoa(s); }
export function fromBase64(s, label='base64'){ if(typeof s!=='string'||s.length%4!==0||!b64re.test(s)) throw new Error(`malformed base64: ${label}`); return Uint8Array.from(atob(s), c=>c.charCodeAt(0)); }
export function asBytes(v){ if(v instanceof Uint8Array) return v; if(v instanceof ArrayBuffer) return new Uint8Array(v); if(ArrayBuffer.isView(v)) return new Uint8Array(v.buffer, v.byteOffset, v.byteLength); if(typeof Blob!=='undefined' && v instanceof Blob) throw new Error('Blob requires async bytes'); throw new Error('unsupported media byte source'); }
export async function canonicalBytes(v){ if(typeof Blob!=='undefined' && v instanceof Blob) return new Uint8Array(await v.arrayBuffer()); return asBytes(v); }
export async function sha256Hex(v){ const d=await cryptoImpl.subtle.digest('SHA-256', await canonicalBytes(v)); return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join(''); }
async function derive(password, salt, iterations=BACKUP_KDF_ITERATIONS){ if(iterations!==BACKUP_KDF_ITERATIONS) throw new Error('unsupported KDF iterations'); const base=await cryptoImpl.subtle.importKey('raw', te.encode(password), 'PBKDF2', false, ['deriveKey']); return cryptoImpl.subtle.deriveKey({name:'PBKDF2',salt,iterations,hash:'SHA-256'}, base, {name:'AES-GCM',length:256}, false, ['encrypt','decrypt']); }
function assertPlain(p){ if(!p||typeof p!=='object'||Array.isArray(p)) throw new Error('payload must be object'); const db=p.db||{}; let objs=0, colls=0; for(const [k,v] of Object.entries(db)){ if(Array.isArray(v)){ colls++; objs+=v.length; } } if(colls>BACKUP_LIMITS.maxCollections||objs>BACKUP_LIMITS.maxObjects) throw new Error('object limits exceeded'); }
export async function normalizeMediaItem(item){ if(!item||typeof item!=='object') throw new Error('invalid media item'); const id=String(item.id||''); if(!id) throw new Error('media id missing'); const mime=String(item.mime||item.type||'application/octet-stream'); const bytes=await canonicalBytes(item.bytes ?? item.data ?? item.blob); if(bytes.byteLength>BACKUP_LIMITS.maxMediaBytes) throw new Error('per-media size limit exceeded'); const sha256=await sha256Hex(bytes); return {id,mime,size:bytes.byteLength,sha256,bytes}; }
async function mediaManifest(media){ const out=[]; let total=0; for(const m of media||[]){ const n=await normalizeMediaItem(m); total+=n.size; if(out.length>=BACKUP_LIMITS.maxMediaCount) throw new Error('media count limit exceeded'); if(total>BACKUP_LIMITS.maxTotalMediaBytes) throw new Error('total media size limit exceeded'); out.push({...n, bytesBase64:toBase64(n.bytes)}); } return out; }
export async function createEncryptedBackup({db,cfg,media=[]}, password, {mode='complete'}={}){ if(!password) throw new Error('backup password required'); const mediaItems = mode==='complete' ? await mediaManifest(media) : []; const payload={schema:'architect.encryptedPortableBackup',version:BACKUP_SCHEMA_VERSION,mode,db,cfg,media:mediaItems}; assertPlain(payload); const pt=te.encode(JSON.stringify(payload)); if(pt.byteLength>BACKUP_LIMITS.maxJsonBytes) throw new Error('plaintext limit exceeded'); const salt=cryptoImpl.getRandomValues(new Uint8Array(16)); const iv=cryptoImpl.getRandomValues(new Uint8Array(12)); const key=await derive(password,salt); const ct=new Uint8Array(await cryptoImpl.subtle.encrypt({name:'AES-GCM',iv},key,pt)); return {schema:'architect.encryptedPortableBackup.envelope',version:1,kdf:{name:'PBKDF2-SHA-256',iterations:BACKUP_KDF_ITERATIONS,salt:toBase64(salt)},alg:{name:'AES-GCM',length:256,iv:toBase64(iv),tagLength:128},ciphertext:toBase64(ct),ciphertextBytes:ct.byteLength}; }
export function validateEnvelope(e){ if(!e||typeof e!=='object'||Array.isArray(e)) throw new Error('invalid envelope schema'); if(e.schema!=='architect.encryptedPortableBackup.envelope'||e.version!==1) throw new Error('unsupported envelope version/schema'); if(!e.kdf||e.kdf.name!=='PBKDF2-SHA-256'||e.kdf.iterations!==BACKUP_KDF_ITERATIONS) throw new Error('unsupported KDF parameters'); if(!e.alg||e.alg.name!=='AES-GCM'||e.alg.length!==256||e.alg.tagLength!==128) throw new Error('unsupported algorithm parameters'); const salt=fromBase64(e.kdf.salt,'salt'), iv=fromBase64(e.alg.iv,'iv'), ct=fromBase64(e.ciphertext,'ciphertext'); if(salt.byteLength!==16||iv.byteLength!==12) throw new Error('invalid algorithm sizes'); if(ct.byteLength!==e.ciphertextBytes||ct.byteLength>BACKUP_LIMITS.maxCiphertextBytes) throw new Error('decoded ciphertext size invalid'); return {salt,iv,ct}; }
export async function decryptAndValidateBackup(envelope,password){ const {salt,iv,ct}=validateEnvelope(envelope); const key=await derive(password,salt); let pt; try{ pt=new Uint8Array(await cryptoImpl.subtle.decrypt({name:'AES-GCM',iv},key,ct)); }catch{ throw new Error('backup password or authentication failed'); } if(pt.byteLength>BACKUP_LIMITS.maxJsonBytes) throw new Error('decoded plaintext size invalid'); let payload; try{ payload=JSON.parse(td.decode(pt)); }catch{ throw new Error('invalid decrypted JSON'); } await validateManifest(payload); return payload; }
export async function validateManifest(p){ if(!p||p.schema!=='architect.encryptedPortableBackup'||p.version!==BACKUP_SCHEMA_VERSION) throw new Error('unsupported payload schema'); if(!['data','complete'].includes(p.mode)) throw new Error('unsupported backup mode'); if(!p.db||typeof p.db!=='object'||!p.cfg||typeof p.cfg!=='object') throw new Error('manifest consistency failed'); assertPlain(p); if(!Array.isArray(p.media)) throw new Error('media manifest missing'); if(p.mode==='data'&&p.media.length) throw new Error('data-only backup cannot contain media'); let total=0; const seen=new Set(); for(const m of p.media){ if(!m||typeof m!=='object'||seen.has(m.id)) throw new Error('manifest consistency failed'); seen.add(m.id); const bytes=fromBase64(m.bytesBase64,'media bytes'); total+=bytes.byteLength; if(bytes.byteLength!==m.size||bytes.byteLength>BACKUP_LIMITS.maxMediaBytes||total>BACKUP_LIMITS.maxTotalMediaBytes) throw new Error('media size limit failed'); if(await sha256Hex(bytes)!==m.sha256) throw new Error('media hash mismatch'); } return true; }
export async function restoreTransactionally(payload, store, {destination='new', targetProfileId, profileName='Restored profile', confirmReplace=false}={}){ await validateManifest(payload); if(destination==='replace'&&!confirmReplace) throw new Error('destructive replacement confirmation required'); const before=await store.snapshot(); const targetId = destination==='new' ? await store.createProfile(profileName, {deferActivate:true}) : targetProfileId; const written=[]; try{ await store.writeDb(targetId, payload.db); await store.writeCfg(targetId, payload.cfg); for(const m of payload.media){ const bytes=fromBase64(m.bytesBase64,'media bytes'); await store.writeMedia(targetId, m.id, new Blob([bytes], {type:m.mime}), {mime:m.mime, sha256:m.sha256}); written.push(m.id); } await store.verify(targetId, payload); await store.activateProfile(targetId); return {profileId:targetId,mediaWritten:written.length}; }catch(e){ await store.rollback(before, {targetId,writtenMedia:written}); throw e; } }
